### ISSUE TITLE
What is the point of the box-sizing mixin?

### ISSUE THREAD

**Issue by KittyGiraudel** [manuelitox/mini.scss#1]

**Comment by manuelitox** [comment]
Hey there.

Really now it haven't much sense.

Previously, I was using it for apply prefixes at property. Later, I began to use postcss for this point and the box-sizing mixin is only to validate that the values are corrects (content-box, border-box, initial, inherit).

I was thinking this weekend and believe that I go to delete it.

Thanks for your comment @HugoGiraudel

**Comment by KittyGiraudel** [comment]
No problem. :)
